### ISSUE TITLE
[PE-D][Tester C] Missing error messages 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T15-3/tp#75] opened 2024-04-05 18:02 UTC
For example, when entering an invalid date, there is no error message to let the user know what went wrong. This hinders the user usability.

![image.png](https://raw.githubusercontent.com/larainezo/ped/main/files/f7cb61d5-d89a-4b69-af10-c8e1f1c0a347.png)

Similar for unmarking of attendance and other commands

![image.png](https://raw.githubusercontent.com/larainezo/ped/main/files/c658179d-98ab-40e2-ae16-c7a031de6af9.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: larainezo/ped#6

**Comment by casaarlai** [comment] 2024-04-09 09:33
Closed as this is a duplicate of an existing issue that we will fix

**Closed as not planned by casaarlai** 2024-04-09 09:33 UTC
Labels: must fix, duplicate
